### PR TITLE
Show system prompt in Dev UI

### PR DESCRIPTION
**Pull request by MichaelDoyle**
image

### CODE REVIEW

**Review by davidoort — APPROVED** [review]
Thanks so much @MichaelDoyle !! Will add this to the rest of our plugins too

**Review by davidoort — COMMENTED** [review]
Did you purposefully leave gpt3.5turbo untouched?

**Comment by MichaelDoyle** [comment]
> Did you purposefully leave gpt3.5turbo untouched?

Complete oversight on my part. Updated!

**Comment by MichaelDoyle** [comment]
> Thanks so much @MichaelDoyle !! Will add this to the rest of our plugins too

Awesome! If you want to support a system prompt for a multi-turn model that doesn't natively support system messages, we also have a middleware you can load for this.

e.g.) https://github.com/firebase/genkit/blob/main/js/plugins/googleai/src/gemini.ts#L390

**Review by EPMatt — APPROVED** [review]

**Pull request merged**
