### PR TITLE
deps!: migrate plugins to genkit 0.9.0

### PR DESCRIPTION
**Pull request by EPMatt**
Copied from #155.

_Before you submit a pull request, please make sure you have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md)._

**This pull request is related to:**

- [ ] A bug
- [ ] A new feature
- [ ] Documentation
- [x] Other: The `next` version of Genkit (0.9) has many breaking changes for the plugin API. This PR migrates some 3P plugins to `0.9`.

**I have checked the following:**

- [x] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
- [x] I have added new tests (for bug fixes/features);
- [ ] I have added/updated the documentation (for bug fixes / features).

**Description:**
Migrate several 3P plugins to `0.9`
**Related issues:**
https://github.com/firebase/genkit/issues/1088

### CODE REVIEW

**Comment by EPMatt** [comment]
@all-contributors add @cabljac  as code, tests and documentation contributor

**Comment by cabljac** [comment]
hm seems like groq tests are failing, want me to go in and fix?

**Comment by EPMatt** [comment]
@cabljac didn't see your comment - I was already on it. Thank you again for your contribution! 🔥

**Review by pavelgj — APPROVED** [review]

**Comment by EPMatt** [comment]
@xavidop thanks for sharing! Would you be up to push your suggested changes here? It looks like it could be a quick task, as you also already implemented the regression fix in your plugins.

**Comment by xavidop** [comment]
> @xavidop thanks for sharing! Would you be up to push your suggested changes here? It looks like it could be a quick task, as you also already implemented the regression fix in your plugins.

@EPMatt sure thing, should I commit in this branch or create a new branch + another PR?

**Comment by EPMatt** [comment]
@xavidop amazing, please make a new PR based on top of this. 
Given the urgency of the update, I'm gonna to bypass sonarcloud and merge this with a note to plugin maintainers to improve test coverage in the future. It looks like some plugins even don't have tests configured.

Thanks to all the people involved in this PR for contributing!

**Comment by xavidop** [comment]
@EPMatt https://github.com/TheFireCo/genkit-plugins/pull/161

**Pull request merged**
