### PR TITLE
feat: azure-openai plugin

### PR DESCRIPTION
**Pull request by xavidop**
_Before you submit a pull request, please make sure you have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md)._

**This pull request is related to:**

- [ ] A bug
- [x] A new feature
- [ ] Documentation
- [ ] Other (please specify)

**I have checked the following:**

- [x] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
- [x] I have added new tests (for bug fixes/features);
- [x] I have added/updated the documentation (for bug fixes / features).

**Description:**
I added the Azure plugin with support for LLMs, embeddings, Whisper, tts, dalle3.

**Related issues:**
Please, link the related issues that this pull request will resolve here (if any).

### CODE REVIEW

**Review by davidoort — DISMISSED** [review]
LFG! Awesome work on this!

**Comment by davidoort** [comment]
@all-contributors add @xavidop  as contributor for code, docs, tests

**Comment by xavidop** [comment]
> You could consider linking to the plugin from the top-level readme of the repo

@davidoort added!

**Review by davidoort — APPROVED** [review]
Ready to go!

**Pull request merged**
