### PR TITLE
Feat: Graphs

### PR DESCRIPTION
**Pull request by debkanchan**
**This pull request is related to:**

- [ ] A bug
- [x] A new feature
- [x] Documentation
- [ ] Other (please specify)

**I have checked the following:**

- [x] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
- [ ] I have added new tests (for bug fixes/features);
- [ ] I have added/updated the documentation (for bug fixes / features).

**Description:**
This PR enables devs to build directed graphs like LangGraph on top of flows to provide a foundation for building agents with Genkit.

Notable points:
- This is just a directed graph, not a directed acyclic graph. Letting each flow define which flow is next provides a nicer DX compared to edges and more control.

### CODE REVIEW

**Comment by debkanchan** [comment]
@davidoort @cabljac does this look good? anything you guys wanna add/modify before I write docs and tests?

**Comment by davidoort** [comment]
I'm afk atm, maybe @Dabolus can have a look?

**Comment by cabljac** [comment]
maybe a removeNode would be useful.

My DAG stuff i'm using in an existing project, so I may take that code and put it elsewhere :)

**Comment by debkanchan** [comment]
> maybe a removeNode would be useful.

I'll add that

**Comment by debkanchan** [comment]
I really want to enable streaming for this. Rn all I can think of a special functions called `addTerminalNode` and make streaming callback available only to the terminal nodes. Is there any better way? @davidoort @Dabolus @cabljac

**Comment by debkanchan** [comment]
Streaming support and remove node added

**Comment by debkanchan** [comment]
Gonna need an illustration for the readme

**Comment by debkanchan** [comment]
@davidoort @Dabolus @EPMatt rebiew plis? 🥺

**Review by Dabolus — COMMENTED** [review]
From a code perspective it looks good to me!
However, I noticed that sometimes the plugin is referred to as `genkitx-graph` while other times it's referred to as `genkitx-graphs` (plural). Can you uniform the names please?

**Comment by debkanchan** [comment]
> From a code perspective it looks good to me! However, I noticed that sometimes the plugin is referred to as `genkitx-graph` while other times it's referred to as `genkitx-graphs` (plural). Can you uniform the names please?

fixed

**Comment by debkanchan** [comment]
@davidoort @EPMatt rebiew plis?

**Review by davidoort — DISMISSED** [review]
Sorry for taking so long, appreciate the patience and amazing contribution! So stoked to try this!

**Comment by EPMatt** [comment]
@all-contributors add @debkanchan as a code and docs contributor

**Pull request merged**
